sudo: required
dist: trusty
language: node_js
cache:
- npm
notifications:
  email:
    on_success: never
    on_failure: change
matrix:
  include:
  - os: linux
    node_js: lts/*
before_install:
- cd site
install:
- npm install
script:
- npm run build
before_deploy:
- cd site
deploy:
  local_dir: "./.vuepress/dist"
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  fqdn: resume.nishkal.in
  on:
    branch: master
